server:
  port: 8761

spring:
  application:
    name: ms-eureka
  security:
    user:
      name: admin
      password: Ganando10k
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      #defaultZone: http://$eureka:password@{eureka.instance.hostname}:${server.port}/eureka/
       defaultZone: http://admin:Ganando10k@localhost:8761/eureka/
logging:
  level:
    org:
      springframework:
        web: debug
        security: debug