eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:Ganando10k@localhost:8761/eureka/

server:
  port: 8080

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**
        - id: course-service
          uri: http://localhost:9090
          predicates:
            - Path=/api/courses/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/microservices-realm


# Actuator endpoints
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,info

# Logging para debug
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG