server:
  port: 8090

spring:
  application:
    name: ms-student
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studenDb
    username: jlozano
    password: Ganando10k
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    #database-platform: org.hibernate.dialect.MySql8Dialect
    dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/microservices-realm

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://admin:Ganando10k@localhost:8761/eureka/


